CREATE TABLE person(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name varchar UNIQUE NOT NULL,
    born_year int CHECK ( born_year>1900 )
);

CREATE TABLE book(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id int REFERENCES person(id) ON DELETE SET NULL,
    book_name varchar NOT NULL UNIQUE,
    author varchar NOT NULL,
    book_date int CHECK ( book_date > 1800 ),
    taken_at timestamp,
);

INSERT INTO book (person_id, book_name, author, book_date, taken_at) VALUES ( null, 'Код Да Винчи', '	Дэн Браун', 2003, null);
INSERT INTO book (person_id, book_name, author, book_date, taken_at) VALUES ( null, 'Сойка-пересмешница', '	Сюзанна Коллинз', 2010, null);
INSERT INTO book (person_id, book_name, author, book_date, taken_at) VALUES ( null, 'Над пропастью во ржи', 'Дж. Д. Сэлинджер', 1951, null);
INSERT INTO book (person_id, book_name, author, book_date, taken_at) VALUES ( null, 'Повесть о двух городах', 'Чарльз Диккенс', 1859, null);
INSERT INTO book (person_id, book_name, author, book_date, taken_at) VALUES ( null, 'Великий Гэтсбих', 'Ф. Скотт Фицджеральд', 1925, null);
INSERT INTO book (person_id, book_name, author, book_date, taken_at) VALUES ( null, 'Маленький принц ', 'Антуан де Сент-Экзюпери', 1943, null);
INSERT INTO book (person_id, book_name, author, book_date, taken_at) VALUES ( 1, 'Гарри Поттер и философский камень', 'ЧДжоан Роулинг', 1997, '2023-04-03 16:59:59.281000');
INSERT INTO book (person_id, book_name, author, book_date, taken_at) VALUES ( null, 'Крестный отец', '	Марио Пьюзо', 1969, null);


INSERT INTO person (full_name, born_year) VALUES ( 'Жданов Антон Николаевич', 1998);
INSERT INTO person (full_name, born_year) VALUES ( 'Семёнов Вася Игоревич', 1996);
INSERT INTO person (full_name, born_year) VALUES ( 'Фёдоров Ян Валерьевич', 1998);
INSERT INTO person (full_name, born_year) VALUES ( 'Голубин Глеб Геннадьевич', 1992);

